apiVersion: v1
kind: Pod
metadata:
  name: imori-pod-file-transfer # replace with "${USER_NAME}-{POD_NAME}"
  namespace: ucsd-haosulab
spec:
  containers:
    - name: gpu-container
      image: centos:centos7
      # imagePullPolicy: Always
      args: ["sleep", "infinity"]
      resources:
        limits:
          memory: 100Mi
          cpu: 100m
          # nvidia.com/gpu: 1
        requests:
          memory: 100Mi
          cpu: 100m
          # nvidia.com/gpu: 1
      volumeMounts:
        - name: imori-fast-vol
          mountPath: /imori-fast-vol
  volumes:
    - name: imori-fast-vol
      persistentVolumeClaim:
        claimName: imori-fast-vol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nautilus.io/group
                operator: In
                values:
                  - haosu
              # - key: nvidia.com/gpu.product
              #   operator: In
              #   values:
              #     - NVIDIA-GeForce-RTX-2080-Ti