apiVersion: v1
kind: Pod
metadata:
  name: imori-pod-glpointrast # replace with "${USER_NAME}-{POD_NAME}"
  namespace: ucsd-haosulab
spec:
  containers:
    - name: gpu-container
      image: gitlab-registry.nrp-nautilus.io/imori/cuda_py37_glpointrast_env:latest # docker image
      # imagePullPolicy: Always
      args: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "1"
          memory: "8Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "2"
          memory: "8Gi"
          nvidia.com/gpu: "1"
      volumeMounts:
        - name: imori-fast-vol
          mountPath: /imori-fast-vol
  volumes:
    - name: imori-fast-vol
      persistentVolumeClaim:
        claimName: imori-fast-vol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nautilus.io/group
                operator: In
                values:
                  - haosu
              - key: gpu-type
                operator: In
                values:
                  - 1080Ti
                  - 2080Ti